name: build_clickhouse_format

env:
  clickhouse_version: "23.11.3.23"

on:
  push:
    branches:
      - 'deploy'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:clickhouse-format-docker"
          push: ${{ github.event_name != 'pull_request' }}
          tags: clickhouse-format-docker:latest,clickhouse-format-docker:${{env.clickhouse_version}}
          build-args: ["CLICKHOUSE_VERSION=${{env.clickhouse_version}}"]

      # - name: Update repo description
      #   uses: peter-evans/dockerhub-description@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     repository: emirkmo/clickhouse-format-docker