services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./clickhouse_format_service:/app/clickhouse_format_service
    restart: always
    env_file:
      - .env
    # develop:
    #   watch:
    #     - path: ./clickhouse_format_service
    #       action: sync
    #       target: /app/clickhouse_format_service

  caddy:
    container_name: caddy
    restart: unless-stopped
    build:
      context: ./caddy
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
    depends_on:
      - api
    environment:
      PROXY_BACKEND: api
      PROXY_PORT: 8080
      DOMAIN: ${DOMAIN}

volumes:
  caddy_data:
  caddy_config:

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./config:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - api
  #     - ch-format

